name: Deploy firebase functions and firestore
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "credentials.json"
          # json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          json: '{"type":"","project_id":"","private_key_id":"","private_key":"","client_email":"","client_id":"","auth_uri":"","token_uri":"","auth_provider_x509_cert_url":"","client_x509_cert_url":"","universe_domain":""}'

      - name: view credentials content
        run: |
          ls -la
          cat credentials.json

      - name: Set environment variable with path to credentials.json
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$(readlink -f credentials.json)" >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn

      - name: Install firebase tools
        run: yarn global add firebase firebase-tools

      - name: Deploy functions
        run: cd functions && yarn run deploy --debug
